//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVReader.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgentsRecordsEntities : DbContext
    {
        public AgentsRecordsEntities()
            : base("name=AgentsRecordsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RegisterContact> RegisterContacts { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<PeopleWhoContactU> PeopleWhoContactUs { get; set; }
    }
}
