//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVReader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterContact
    {
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Plot_Location { get; set; }
        public string Plot_Size { get; set; }
        public string Plot_No { get; set; }
    }
}
